apiVersion: v2
name: spark-operator-platform
description: Platform-managed Spark Operator
type: application
version: 0.1.0
dependencies:
  - name: spark-operator
    version: 2.5.1
    repository: https://kubeflow.github.io/spark-operator
