---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-task
  namespace: airflow
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-workload
  namespace: {{ .Values.global.sparkWorkloadNamespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
