opentelemetry-collector:
  mode: deployment
  image:
    repository: otel/opentelemetry-collector-contrib
  replicaCount: 1
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 200m

  alternateConfig:
    extensions:
      health_check:
        endpoint: "[::]:13133"

    processors:
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
      batch: {}

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "[::]:4317"
          http:
            endpoint: "[::]:4318"

    exporters:
      otlphttp:
        endpoint: http://loki.monitoring:3100/otlp
      debug:
        verbosity: basic

    service:
      extensions: [health_check]
      pipelines:
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlphttp, debug]

  ports:
    jaeger-compact:
      enabled: false
    jaeger-thrift:
      enabled: false
    jaeger-grpc:
      enabled: false
    zipkin:
      enabled: false
    metrics:
      enabled: false
