apiVersion: v2
name: kubecost-platform
description: Platform-managed Kubecost
type: application
version: 0.1.0
dependencies:
  - name: kubecost
    version: 3.2.1
    repository: https://kubecost.github.io/kubecost/
