kubecost:
  networkCosts:
    enabled: true
  serviceAccount:
    create: false
    name: kubecost-aws
  cloudCost:
    serviceAccountName: kubecost-aws
  extraObjects:
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: kubecost-aws
        namespace: kubecost
