airflow:
  fernetKeySecretName: airflow-fernet-key
  jwtSecretName: airflow-jwt-secret
  apiSecretKeySecretName: airflow-api-secret-key
  executor: KubernetesExecutor
  rbac:
    create: true
  dags:
    persistence:
      enabled: false
  logs:
    persistence:
      enabled: false
  apiServer:
    resources:
      limits:
        memory: 900Mi
  scheduler:
    resources:
      limits:
        memory: 900Mi
  triggerer:
    resources:
      limits:
        memory: 900Mi
    persistence:
      enabled: false
  dagProcessor:
    dagBundleConfigList:
      - name: dags-repository
        classpath: airflow.providers.git.bundles.git.GitDagBundle
        kwargs:
          tracking_ref: master
          refresh_interval: 300
          submodules: false
          prune_dotgit_folder: true
          git_conn_id: git_dags
    resources:
      limits:
        memory: 900Mi
  extraEnv: |
    - name: AIRFLOW_CONN_GIT_DAGS
      value: git://https%3A%2F%2Fgithub.com%2FVictorCoutinho86%2Fdags.git
    - name: AIRFLOW__WEBSERVER__EXPOSE_CONFIG
      value: "true"
  workers:
    resources:
      limits:
        memory: 900Mi
    kubernetes:
      serviceAccount:
        create: false
        name: airflow-task
    celery:
      persistence:
        enabled: false
    serviceAccount:
      create: false
      name: airflow-task
  redis:
    enabled: false
    persistence:
      enabled: false
  createUserJob:
    useHelmHooks: false
    applyCustomEnv: false
  migrateDatabaseJob:
    useHelmHooks: false
    applyCustomEnv: false
    jobAnnotations:
      argocd.argoproj.io/hook: Sync
