airflow:
  defaultAirflowTag: "3.3.0"
  airflowVersion: "3.3.0"
  fernetKeySecretName: airflow-fernet-key
  jwtSecretName: airflow-jwt-secret
  apiSecretKeySecretName: airflow-api-secret-key
  executor: KubernetesExecutor
  postgresql:
    enabled: false
  data:
    metadataSecretName: airflow-db-credentials
  rbac:
    create: true
  dags:
    persistence:
      enabled: false
  logs:
    persistence:
      enabled: false
  apiServer:
    replicas: 2
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            component: api-server
    startupProbe:
      failureThreshold: 30
      periodSeconds: 10
    livenessProbe:
      timeoutSeconds: 20
    resources:
      requests:
        memory: 512Mi
      limits:
        memory: 900Mi
  scheduler:
    replicas: 2
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            component: scheduler
    startupProbe:
      failureThreshold: 30
      periodSeconds: 10
    livenessProbe:
      timeoutSeconds: 60
    resources:
      requests:
        memory: 256Mi
      limits:
        memory: 900Mi
  triggerer:
    livenessProbe:
      timeoutSeconds: 60
    resources:
      requests:
        memory: 256Mi
      limits:
        memory: 900Mi
    persistence:
      enabled: false
  dagProcessor:
    livenessProbe:
      timeoutSeconds: 60
    dagBundleConfigList:
      - name: dags-repository
        classpath: airflow.providers.git.bundles.git.GitDagBundle
        kwargs:
          tracking_ref: master
          refresh_interval: 300
          submodules: false
          prune_dotgit_folder: true
          git_conn_id: git_dags
    resources:
      limits:
        memory: 900Mi
  extraEnv: |
    - name: AIRFLOW_CONN_GIT_DAGS
      value: git://https%3A%2F%2Fgithub.com%2FVictorCoutinho86%2Fdags.git
    - name: AIRFLOW__WEBSERVER__EXPOSE_CONFIG
      value: "non-sensitive-only"
    - name: _PIP_ADDITIONAL_REQUIREMENTS
      value: "apache-airflow-providers-amazon[s3fs]"
  statsd:
    enabled: true
  config:
    secrets:
      backend: airflow.providers.cncf.kubernetes.secrets.kubernetes_secrets_backend.KubernetesSecretsBackend
      backend_kwargs: '{"connections_label": "airflow.apache.org/connection-id", "variables_label": "airflow.apache.org/variable-key"}'
    metrics:
      statsd_on: "True"
      statsd_host: localhost
      statsd_port: "9125"
      statsd_prefix: airflow
  workers:
    resources:
      limits:
        memory: 900Mi
    kubernetes:
      serviceAccount:
        create: false
        name: airflow-task
    celery:
      persistence:
        enabled: false
    serviceAccount:
      create: false
      name: airflow-task
  redis:
    enabled: false
    persistence:
      enabled: false
  createUserJob:
    useHelmHooks: false
    applyCustomEnv: false
  migrateDatabaseJob:
    useHelmHooks: false
    applyCustomEnv: false
    jobAnnotations:
      argocd.argoproj.io/hook: Sync
