apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    admin-user: AgAal+PXgboggka+FakhAdf+Nnn4iQ7Htma9PGPwkiQhKV6EE4RsElFCcdVmlSCMJA3UxdW0aBP+ONV9N4VuSiF8Bj56jC0IQ7k9ZLaYrvAUCoGfuSNcUpyAvp/LaDTS/pdU7SrcE2Qkm43RNzU2wB9Z0gsG/S2k4it0gUOUYQ8Bpn827nlA4vj95SEUDizLxHKvCLHYVDsx7pssY6pWslEq89DySAJSECXhmTE9JzGHqr9fdKRl9/QQ7Nsr8PVqAWQW1j+Lzvb17lPg89kQe0T6WZ/hWRBWphyOJr8PlCL6haeRQVZJnHd79qZU1TXQ3jsnXCvoDIGewT8CiIHu0q0U58vHzHObUyGIB/POh4Hvu3cWs4JISipfzZhIVJkK9iOBA4bYpjJT65EbUvE1lZ0LZY2xUfx5h7PqjWiW9+bQuf9yCOqKbOdWAUdt0yAcZWIEu/5QO0uN0KHLmxMz6nyr8TTVToiI8sZA8g5vfmrREe85f7mO5EmPF3S/y9KWcKTqFnScNSIi4uCAB/RhnXTwXRcifZLyYr9wL8jg4NELyjkrH3tazHU5zlIekDZ8fEs08MZo+VJWZB0AeGYwmNFUa+ESnXqlTMku3zazzOo3qcn/UmwZDO1adhbY6kBiEsrzhb8KHVXg/C8ZfRon+jOP468mHPd2+nL5jsGFkAQai0wD+I8Wh3vjnY+LHqP7aUEQdVTnVg==
    admin-password: AgCDJ6YOfuriaVJ3p5qEvQ9MT2C02QZANcgqsmZMis9s9G/Avv4miZ31LRoQtAUyjS4dWxtnJSzzrYDpRkVm9/RElbMavhWABaVM8FhxlaUOUMOc8icbcd7TPpc3ypku8Miqhk/xQ1Xk7NR5TkYhxWVD2N4VZX334qS0xzoI8tRajD/yYIezUR1FRbm23MbfGaYsU1f2EGgCX32JrR4xCIRYUd9DQtti1O4aleFmNKO2Bxepk3arf5br4pEA7YqwwOzNlzNLbkAWFwasU+qlaKd6P6i0dTgleyzpa1G2Wpr1PXep1zlivIfwoJUivNTh4bR9We6mZ+uxEDYnIDxP9ZcI+DypyE0aqqCLOZ1f3w/io8a/5eY8s+S06NtWInGgWGX3OJwpUcaYyULwX1mb7B/g+u5NQM+McmOoYMzGEF4QNCXg7rQ9h/3rgb6ncbKhHJh+VsaHInS1p2VwlA1jh/AyoB5LrQOhl0YoxPP94PKhjDAodgN9xoQ6mirulivoQ/lSjJaVmyShQEN441Q+LfIBh2x+Fmo9kL7HMjpogvetiee/gI+OWHI1cd0KMj0A1oTK86k46ydc/cGz95tP5T0Y15p8FtFN0OBGPVBM9kQniz/WUnlWhLv9wH1PWRF25ExZn/MgjefVAjkSPLqwxTne0NWWJkkIr6Myjt0A9okWGJySlWZPpZKTBvajwYMvVo57IZ71OgUgcnE9/06j0gaYrnvy4vSr
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
      labels:
        app.kubernetes.io/part-of: monitoring
    type: Opaque
