apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    admin-user: AgCHANGE_ME_RUN_seal_secrets_sh
    admin-password: AgCHANGE_ME_RUN_seal_secrets_sh
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
      labels:
        app.kubernetes.io/part-of: monitoring
    type: Opaque
