apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    admin-user: AgCWhf6rTAXrcXXyCK57GnP4AxOcDhG1f4A18c0leO72Yo6LMHD0/cO4jzAcH3KOjlqBBZt2LDThcznvW9KnD/FMBNHSBTnabfIUixtteaZfoAkAr8qS6/BMMBJpnh5bCoQfOjhxskD1eje+ansRXJy4EbbHgcv2UgV1WcWHfYECR4giBwC4140yvK4Zn66p4XDgZADkv91XP71EsF8S18JMCgjoi2MMY8yh8CffIf1DLiDZjhq/w9wXBnZ53qCXlP1qUpwG3XPPsPXD3/LwhosNFcgLUnz16P1Z97HS2e3Pmu1Uoq+N6AwtAarRW37mXcunz4r8w9uFYURDHNOLLK1AFj3QT9zQVX0DPEoKwxHOSAnA9HWehf/SAO/hupPPJWe9umODUVdoCj23tm75vEG7MvVIr7XFwlSRbsBpboSRVidaemC1BQS9R3XW5GfEtH/KDlqBIMlwGN7V8vn1HmafqOuUV5Et/+NRXX2aJcRNrGNxc3JnuwlpqrIDYwz95/+riBBMh4eXdwezEltZLZlR3hJyONebH7F5HZdQIGacWF787r6ylmA49PzEvJZ4Yoo7zOELXft1t49G3E4qSNS5HIEkJKbN0zT51iY6YZys02aDE7vP6kfLruBNgBybdDZgVMYHZQWpUU1R95gdvjujhoYMVSEzkzHS9TBdrLaCn3hCJztQYU61wu3kgZWXxvhUhzNhHA==
    admin-password: AgCBDGO7pO+3DmUKDFHT1t9SGm0PGUBw+1Yf255H6urIX/+haAeJfB9j2vO7J54oAjb7Jg3mA15xSZa6q8IgfFnjwTaNNYGvioDpp1KVTjbh8mxJ1XRtOIAG9apT5tHVGB6tiKBcLoZapR9jBG3Lzpcw320X4zj6t7IR7wEF2R6SuIXz5XqkJyZgizGoobTEI8CdbN8Ydyl1jtrOoLSq1NXuNzGN3H60lPFHzzWb5OQDNQ6ANh4TdKzFc3L9k/x1h6ODi91DP6ZvLjcqTFOzBxTqJXGEedht90SBw/1KP3qNeaPiWVMpD9MCDq37DesvSOkX+r8qO1UKAuqkTD7+iwMhubjAubXV3ImOflsvoTtIqe1OVSm/1DKAHJUBrrq1vBWvhMgqHNtMe49xkz2NoNUbGRO2ro4373yxm5vgzZXmOaXKQo2UZ3oYEpydQtgyq0rR/RkH5OjNafFhjo4roj7V399mFXA5fNMv6tvH7vPeGlYM5KCy/LNWsY+x0dSklbFHdJfV5H7+SyLF6Kcz1NgKo/y4GmHwsWbs7BO/0oIVg+RrmgfuNjTNO+BjW+Bw/PZjI3cmYRnj9UfPtHj0McKFfgAC9R/t66AAB/CyT2FqCgFB7GfFWqLCCJeMrb4K39XID1wijnbpTrb6WTxG7aqGG/k+a7Pn/DvqGqmmnA/c60dhKGn+pDuwdoBKr4eGnl/BLBevbqaolP5SttjpxmegIFouEEk7
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
      labels:
        app.kubernetes.io/part-of: monitoring
    type: Opaque
