apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: public.ecr.aws/karpenter
    chart: karpenter
    targetRevision: {{ .Values.versions.karpenter | quote }}
    helm:
      releaseName: karpenter
      values: |
        settings:
          clusterName: {{ .Values.global.clusterName | quote }}
          interruptionQueue: {{ .Values.karpenter.interruptionQueueName | quote }}
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://airflow.apache.org
      chart: airflow
      targetRevision: {{ .Values.versions.airflow | quote }}
      helm:
        releaseName: airflow
        valueFiles:
          - $values/gitops/values/airflow.yaml
    - repoURL: {{ .Values.global.repoURL | quote }}
      targetRevision: {{ .Values.global.targetRevision | quote }}
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://kubecost.github.io/cost-analyzer
    chart: cost-analyzer
    targetRevision: {{ .Values.versions.kubecost | quote }}
    helm:
      releaseName: kubecost
      values: |
        global:
          clusterId: {{ .Values.global.clusterName | quote }}
        prometheus:
          server:
            global:
              external_labels:
                cluster_id: {{ .Values.global.clusterName | quote }}
  destination:
    server: https://kubernetes.default.svc
    namespace: kubecost
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://kubeflow.github.io/spark-operator
    chart: spark-operator
    targetRevision: {{ .Values.versions.sparkOperator | quote }}
    helm:
      releaseName: spark-operator
      values: |
        webhook:
          enable: true
  destination:
    server: https://kubernetes.default.svc
    namespace: spark-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
