apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-root
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL | quote }}
    targetRevision: {{ .Values.targetRevision | quote }}
    path: gitops/root
    helm:
      parameters:
        - name: global.repoURL
          value: {{ .Values.repoURL | quote }}
        - name: global.targetRevision
          value: {{ .Values.targetRevision | quote }}
        - name: global.clusterName
          value: {{ .Values.clusterName | quote }}
        - name: global.awsRegion
          value: {{ .Values.awsRegion | quote }}
        - name: global.vpcId
          value: {{ .Values.vpcId | quote }}
        - name: global.domain
          value: {{ .Values.domain | quote }}
        - name: global.certificateArn
          value: {{ .Values.certificateArn | quote }}
        - name: global.karpenterQueueName
          value: {{ .Values.karpenterQueueName | quote }}
        - name: global.karpenterNodeRoleName
          value: {{ .Values.karpenterNodeRoleName | quote }}
        - name: global.sparkWorkloadNamespace
          value: {{ .Values.sparkWorkloadNamespace | quote }}
        - name: global.airflowLogsBucket
          value: {{ .Values.airflowLogsBucket | quote }}
        - name: global.kubecostAthenaAccountId
          value: {{ .Values.kubecostAthenaAccountId | quote }}
          forceString: true
        - name: global.kubecostAthenaDatabase
          value: {{ .Values.kubecostAthenaDatabase | quote }}
        - name: global.kubecostAthenaTable
          value: {{ .Values.kubecostAthenaTable | quote }}
        - name: global.kubecostAthenaQueryResultsBucket
          value: {{ .Values.kubecostAthenaQueryResultsBucket | quote }}
        - name: global.kubecostAthenaWorkgroup
          value: {{ .Values.kubecostAthenaWorkgroup | quote }}
        - name: global.cnpgBackupBucket
          value: {{ .Values.cnpgBackupBucket | quote }}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
