apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-admin-credentials
  namespace: airflow
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    admin-password: AgAKgltRdMMF2/FOp/nY89/DNSiPZpeMY1UJJLUcbHNImMVnUTjIV+dXD1MVwtzM4lf67ckUY9LCUS02cOFdp3hINUesWzvUZ2HSCFudB2+F43lF3NS7yLwQZezna2mLg1RNMqXBHoZ3nGku2mNK1+AbfwjiZmtTt5a/BubeaaHFpiacVF9DgbRCsUwoUPPNVq3qHmZkA1dGbq65u/ZnjnYKHezgW6PjUq9ViBSSS2AltvvWJ9gG9xguAv0aW3SgTFW6QUjIXq4ilxRL4USKL8dT+1+ueZUCD3aKUqRxqRezJ40BlpSNcre4NEqjDFzhPw7BVzD01gcvrQyOaq/NFLU5ouHBajzLlMEcL1+sxK8MWQZGzjJ278nD9pWihVEleJOh5lmxGNNH42C2fdQs1ulALkHT5jKvJWK57v2HQQCf1S4n8F1EGbag7lLi61WZpW3R8DlwIYJRKSW3T9wJIZE4lGeEBjScArVfsqG4cj0A6y3t08Ehjad/0rn4qUBKRgSH3J+TtSwCRTBce/1RtBxzKha778otPgDeYOzXxt8UwDoE/pi113v0UC5tuZwo/0dZAw8qDm0JquOiDi0JP9MGn63FbpHC3UNwY9vaOIjFoHxHGO2d+r/LfXauVQYI6f4TD4DJJNzDtKkEzAX6CqEOx4uZ/usg6wL297/pgd9fuWy8mU0SK8uYB6HV1l5Iyq6IgM8zgW8g+sF9eWb74GBFVG5ZFJS+
  template:
    metadata:
      name: airflow-admin-credentials
      namespace: airflow
      labels:
        tier: airflow
        app.kubernetes.io/part-of: airflow
    type: Opaque
