apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-admin-credentials
  namespace: airflow
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    admin-password: AgCHANGE_ME_RUN_seal_secrets_sh
  template:
    metadata:
      name: airflow-admin-credentials
      namespace: airflow
      labels:
        tier: airflow
        app.kubernetes.io/part-of: airflow
    type: Opaque
