apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-admin-credentials
  namespace: airflow
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    admin-password: AgCBQy+L0RArk1Q+r504Sb8ZhhkOrgMVS2jHkBhFJUS3+PsHn3P4sdtMcWlWaG5HQCEpQZiepN3eAnJB783oPCHiG8A6wZNdCKJM3MRenNnWcmpkYyAjXjtHn/oD7gVi0G0ckwQwHvWjSqUoK8Z8rjZP4koaKaY4y1cMPh2uQ1IMwASVU3+JiMzgUCv8oUEOdQxu/6AxC4f4bSHQj77v5jF0kzCoQcNpv4M7uOm0yIqTgOHgWHJ22zxfOgSXn3mIoIwk9PRWEhboQGPUaSpxJ5Pj+JcIEfM86I/HLFLCL++OZaEKDU1mNoonTZVSBtMGgOz/SLXVlX53+92NR3OghsI7UTEigsHsATj0ifOi9KBuDEMjHCElNVTyo9u5bQOluB8jUZZh1I4wBWx+CeGI1x1svnzaUL8xcloTH+b/AqRbJIR+gGhMp7Ew+sDpbvVxGkYKVZb/HLFIOHfptWdr5dFpICEW55zuIyd0FnOVaACZ2uloPiU7SaSVlcJaPDd+zKanVlyPe0GM+WqSqhapSGObspCt0purpXG3a3jNx35jqUgSY1FxrZLs+X7ZEDGU1OcWBCEM0rINbh26eGGSiNUg+2tV80sL3oPPFWFWqD0fKRWpjPGAorTNjNiyl0E7wZ8jigYQonC6VA8GCqOEy5rEhjzbWY2hnWhk/Cjn9SA+enZv7LAYGtghxr2ZIHz+KUelNCjHhq4mTWFuDp8rf2kEemIgSyos
  template:
    metadata:
      name: airflow-admin-credentials
      namespace: airflow
      labels:
        tier: airflow
        app.kubernetes.io/part-of: airflow
    type: Opaque
