apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-api-secret-key
  namespace: airflow
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    api-secret-key: AgA7az4gxS+zqnRQig9jxEvciFsYXCsqvZSgufXp42fHwVeyL964NTC2MlMmGosmLpuKETIHt5hylcPIUObJrV8wHqWRmHJDpbQRgouxakjFa4nYr55b5bhxeMR1ynGnIKon90bm9ehDXO84USO5mwC1l3OCidryWjiRmS1KoSlVjUlkc9BSejW/56fohQwfUkr8lp5uyp0ClL+YnsHlCXX/25nG5f0jSQBo6ULSPrkADLQsTCGUMprjC/YxHa7A1eMEiwfTgovdJvsDF1WJj8s1gZBuZ/7g9vRYd71SLAcx1rFVnnxg8x7W2fIjomBlRIc3oqbVnVi+PsGzHRhivzEnHvHoyrEK8bkG6u6NfAZg9BT5dqsukXc39CodpPhMU0t7UYK3FMh2Vr4OvMXkUZyzHAwKLO00JVmLap2RgEen5SKudLtKRaz59jA3uBxkb4NjTVTrTIzi8ciLKJtoOHCEiHumvT3TK/N4luSnQGy02cNssmr56PDY5qzBvqM1tG+CojVGJ4VsfpyMFFnN+DKUpf/YoM8vTsbZxIKUYclkJP0wadyuOVb4kNAMdVeC/byJir1qk/P+5wW3DDUPzieKyZh3IkkOgMXBgrkKC1HVAmzs2yjuH9p4TcD0yRhrY1jaHMDrnckA+5CZnjqZYB2KyJnd1O+HERZeqwUNv9rTLpPtJm/UI3LN754WL4TYmthAPmtacfPI7y3reDbW8Y3sl5HJBi1O8xaJq7jYebMWeQ==
  template:
    metadata:
      name: airflow-api-secret-key
      namespace: airflow
      labels:
        tier: airflow
        app.kubernetes.io/part-of: airflow
    type: Opaque
