apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-api-secret-key
  namespace: airflow
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    api-secret-key: AgCBTAypSMR0zOrKM5sqJ8brYZumiq1oQeY4r6cOlayXRELeij4Lxeby0gqK6IlKV0Y2YqqR2Uj04Gl22WgyJWEkBM11z0IAU8NtDjjT7Z/O6rxH/LW20XPP+V67JHXP0q9cJAAbx7GlE9UwXvg1K8qmSsfuoTuSK6mJGS59N6H5zpbM0Pmtpxt6EQEJsfJaKJzakSkI5k8ACxWZgthD1OxBI37NZyYbJXq/B8VoNGWK3W96kgmh3E4iT8kbTOYvf1pnPC5hwRNT0olECfzsDcqExksrlWyYjSvZuyb1U5dx49/aLfL/jtjbWqjPci4e244oZ038UVerf8uvG/gSDM70h9Gj1ukwNx+iT0fhFPGpcBP4SXooK8wxVGJxHip9b2ig02jIS/MnCzZnxNIRpOMrxyapNSywFWFJ9LNe1/w5UD3AYecftnyjMRNqginV/0AQEnMMHigTNQ/xWn0zcnUSAgEZLmJswV0TgHUk9JFc7TQPssHKakaxt3AXe5ZZiIgxRpAxQJ29/cWPlP+B6PUxX92mohMc3+dOexh0v9K+/XYlh+AE4sPJCPtI70RYylEsj3s/pR34CyMaVR3jGkY9XaTC/fSKlJyT+LV7/7+bbhwbO/lroKKMR3hB3+5tYWgEkZ2GPPOZVs5cyO++TNx9YDWNNAfkwB2973Wxe10c36GQcdbjtVf+tItPJdjDGK6H/d5ll5mPsyaZXmWD24dJ6KXrX1mb70Dec2XW5qi0bg==
  template:
    metadata:
      name: airflow-api-secret-key
      namespace: airflow
      labels:
        tier: airflow
        app.kubernetes.io/part-of: airflow
    type: Opaque
