apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-api-secret-key
  namespace: airflow
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    api-secret-key: AgCHANGE_ME_RUN_seal_secrets_sh
  template:
    metadata:
      name: airflow-api-secret-key
      namespace: airflow
      labels:
        tier: airflow
        app.kubernetes.io/part-of: airflow
    type: Opaque
