apiVersion: v1
kind: Secret
metadata:
  name: airflow-api-secret-key
  labels:
    tier: airflow
    app.kubernetes.io/part-of: airflow
type: Opaque
data:
  api-secret-key: {{ .Values.airflow.apiSecretKey | b64enc | quote }}
