apiVersion: v1
kind: Secret
metadata:
  name: airflow-fernet-key
  labels:
    tier: airflow
    app.kubernetes.io/part-of: airflow
type: Opaque
data:
  fernet-key: {{ .Values.airflow.fernetKey | b64enc | quote }}
