apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-fernet-key
  namespace: airflow
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    fernet-key: AgAMTH3lwQahXbIywBqftGSC35oLPRU+WV0lZ3RNUK4KmKWpmvVtPraYbxgKbq3zA6hsabqt1epa47cYw1tSLEbEFFxWp4mVLmYzq8lRcs0kWTZG393CWOMMQnMLECo8MvhewceG/zoMwyaFxkJZfeQW2/gPzqM7pAXmg96SceDEFbOLMhmjAJ4260ysdIjVBV+izxaQkyaq+BD9hCR/9/AkPLL3Tnw4PkjO6+uB7TvDPrMtGacnx/LJYpvkYwjlAEV3KX7IK71pj8ysCOUPgWL3Rz4qifKWq/UF++EoOlgPDrPsVcRkRE6ZfTDeFWncD93KvDbU8t13jmuG6eNsYO1j88JLSreZzd/0wr+yxkJ1VtRtiIpVUciZ0YkZ/6+gdZNJp5UeR1jrRKUhJWGucnhf0O27D2ITk7obPISbekuncvuC3LJmGzorcpuP7OPv9oc8UKO+4ChbdZI14eebyRC+WjA142OBXSxJM1jMfZEwcCZC05hCHFMPu4AgtjaouDCBSicoRBK2nzoQc22g+MBim3kfZYJTFWLbUEiegNEdxHTHIFfoZ3xiQjRjydvmPoXAZyvnXC0nnMPOtVuszQ5tkFM6Aa9wy0GPHSUAgL6Lkqz0ovFWdiGb9ii4tcodXsPZloowTP83h32wbaSCI41NQpMgPpTW6+alEkUtmVW/U+y+QOPks1eThlJvK7IcGK+cSdGnaCwZjmLKvWQlm7xwkPZr+W0c6KC2XqDTlSw7Q2VlkhoXsb5zj/qt
  template:
    metadata:
      name: airflow-fernet-key
      namespace: airflow
      labels:
        tier: airflow
        app.kubernetes.io/part-of: airflow
    type: Opaque
