apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-fernet-key
  namespace: airflow
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    fernet-key: AgAAp1xcU5nqv0hvSDHG5X6Z4bEax5n3scEFqiQP7yxSg3FiJdtGnN1KsCiY3711StOIIOU0YvgMFfWK94kTTqmsvpHdLj+5BgxbsC5mN9VxftPeO+rprcHAw+bIEBJC2z+EMcPmRopi7EEUb8+VnPf8bDP/yUbpFMozQh/prGyCAfdU0qs6LlmGzkKEbPG63pckVzev4S2gygrHXxPIgetZAfzYV8qiO+swOF6qGf/JYUs1CI2L4iuuizYCUl941TDCT2xUMMdJtpB8lTKvLPd/wkXzJUiq/bXeXgJ9mCE5eEa9FqAejtEcrdnHWj2XMHm8xFr//T/hR21mVqGitOzng/etLbavaqMr8cDVsxX//06HcBd0Fua+970Vx+Q2ti0PimbyAZlH8fgffnjQVinbdP0MMtpgpLQRE+PmXMRzDTbZHkqiZCr39Ja2RTR5iIycRFUoiBgAtadVj6L26JBrNLa+OW05+ZFhaHTbeqNsjq+pcWzyt7VFsox6fHqIoot5fr0oDxoNCGkUmdIAlciO8nh5cDaR/r6/7wGqzi53INhRoFp8S/A6mu3pcJsRIbJfAgQVACgErofUxIhhh8fAH0eCu9KdgegRhnz+x8rHO0BKu577/nDY41Xb9bUVA3AsDeCzDwiK9Tat7nemffS3gfL6/x8JrqkXMRJ+ghJDzoWWW1RcIwUQi7CGkB09IvmNgK3iZR+qLHfCAKek0F/DgJk43vZM5nwLdrJMrKtUBY80rctE646BJeni
  template:
    metadata:
      name: airflow-fernet-key
      namespace: airflow
      labels:
        tier: airflow
        app.kubernetes.io/part-of: airflow
    type: Opaque
