apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-fernet-key
  namespace: airflow
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    fernet-key: AgClsS0+YQCsZlJ7/LLL+Gddvjj/rk/ZLoac8axkDxckFOacQTn/ocbZB3IXiB1e3RDv+p+m24virPuB7/Z2ARYJ/yiPLWDr0kjLVTs/k+iH+1JvYrU7TFX+IaBlwe7dnHTauTGSzNhUMD/WDrmgiv4HvgajsTNxB+JD9HF78KuG4DsIBS+ofcyMil6bdWrVFaDmPpNqcLCeFNwc5O1yBW6/27pO8k3zvqyKE0JNYRnon6J2wQkbAJw3GpMh5I7H3gfs6CFaUF0ftEldS1FEH1sW6mb5nQjm6ZWX3nqM6nKflPFYB9aCvL/7kQybPh8C4BZ9Ua3BaU0vQgz2f++Wwhi7b4sj43SUnSF3CZhN0TLNTh8CFAzWRs2kot6jDqI1YPCWwglihAK95f/7i63lpmtfP4YgdieAhQPWuS054IS/4iX7bAmxh6Q3G0/sgC4krjGAT7MqxVOlqI+9OwrQFpnkqPmPNaSuHC0vQ7HYhfsLVT9eKklGMugls7n1iFu7EpYXQDKsdnHDdxtPVNUHES/tKQAiIvS2Zssx6YJck005R7gXwGANxG0Uzrt/jWkkA4NWHAUuLXygQE1pWQqxoTUxzadTnd2JudwdsrnJru26Em+ukpsHRvFJwhLYDEFqTNXm42U9w364DjXkfRbUoFB19DXsUMHvznhd0QpPxdVqc0prtCmotOpIQCqAQJf9X/rTq5GdKuGe26yFEo/kk1e7+iZZ5oJROq9We/ANMAfKtTHtmAsSvYX8bYEe
  template:
    metadata:
      name: airflow-fernet-key
      namespace: airflow
      labels:
        tier: airflow
        app.kubernetes.io/part-of: airflow
    type: Opaque
