apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-jwt-secret
  namespace: airflow
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    jwt-secret: AgBSMYBJ0hNepGUAgLKWKyuBhRrvgobIgBzVbZdK/QWk7KLZwdMocWgj0KDloB+K+O24G+uP7JiGxi8YEx72z4kDcDrs1t0jckZJnSJBemd6aTuVPvt1KYAhd1wGRRJQBqbfm1VZLHraexEk0fKpvRiH/RE4gab2J1nE4aKS4utH6IcFPJLsgyU2Nc4lXhXd5GoH+JDychVJT7TJj/WbqcBmtEc2HXV4KO7HVRaxFK3L0TAnr5+i8gOxAGe20jQEHSjJx6mS6gONx8N8Njc+QDsCNqzYtE8D0CWTqSI21JAncPASOn/AyNK13GxtwOZrkCDXIPrnD24YWnmMH6KnlMCMoMThElEnnetGSV08Nel1vafm8NQOrCmN5cpJixeaov2DW8GpV/D+qDMyGXsXEYaMqV/QsLtpG+8s5jGHGKrj2VoWvVvSei40Blac3lM7MQh4EXnSyWrxqkqbfwY0xLl8RTQBZNKYDhdZBXtIMMREpfnHpnzlDKEaA3tUPK1gJz7UnTfhP/LqqCdZaBgMirqjvyexpfrDwYarbx/grXqEOZ8Za4RnoBJVKlcE48VmCvyAaV6oLW9g6LWrGQesmVBp+V7hajfsK5XG1qcVRmO4JkTn/WAIqz7B5jWbF33x8z2/lOD9D4vcYoZauxG2mrjVSGs+QXxYL1vBk43vkmimC29HOyqma6qLNepaElderDIdWUdfZLUtaP/I+f6wlzK8MS4FZdXZyjNZlS7Tc0UT1tNWJo788qX8HwF5hpzZJ2Y/8JgNyd8ce3nDjTcPEIdL
  template:
    metadata:
      name: airflow-jwt-secret
      namespace: airflow
      labels:
        tier: airflow
        app.kubernetes.io/part-of: airflow
    type: Opaque
