apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-jwt-secret
  namespace: airflow
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    jwt-secret: AgBkcdd4rH1npRSLnIGwfYEjXDdX5altLYWXLjac0thruRm0dNOczJNFGsSQbkDER5YChxoXl/c88kpyxByaLisYQVRkK+c7v8IukbTPGjdQW3ukOGRyjfRmgQVRhRaXdRJpiHFkr0IfPKsEFEuRumS6pbSxf/DSa2u+r6C6yjCUIjL0hrjFxHzTmGER1fGZ9onZqiTdbRbuYO9HJHE9kzJPkKfznRU0n5b0Dy9QaeTr1bqB7xH/xHFOhzPv3+CIU+Bh6DOZoB1pmDxVIiWOpfTlnlmyY7VNEoFOrM7XTqiG54oP+plobTinajEmBoPHzWx5Zdj3yUQDtdKsaPDtzTa6BGyVflBHwOytVVjTtTYpT8Ty1O1krVl101fMpM5OdkxvVd3iFbNt2bVXyCjfI9pYecX2iGaYYblvWEOpB/ni/DTuAU8B6TVfEqyA0pvaHPs99I/mqDYi2R8YWo89R94+cib5oiQe0mjaXQv9bbPaoN61mIP0+QpYboZiLYV/I1TQXmtwe7mqUtPpxcP0cdNmfKdeNYAG+LQozOXcD38jayTN+GfOZVn+N2RUOKaShSl4XNsmdxD/VSU/1PmxD4eGkMMYqpVokzeIYAX6S73wyPZ4bRFLOl4RaSIswYw7aiCXCFSsfPlKrDeED3wcSvDGpOnd68Ei5g1Jy0CQ6wgR3NqXurWc2yQxEbxPVwor+GBbmAWHacetdrtJbPAMYhUFT5lplD2/UHJJpRP7rbHLuVWagTUQqcQMx6wcV0qjg9VVIRZsCjIKf8kWdOcDFyWO
  template:
    metadata:
      name: airflow-jwt-secret
      namespace: airflow
      labels:
        tier: airflow
        app.kubernetes.io/part-of: airflow
    type: Opaque
