apiVersion: v1
kind: Secret
metadata:
  name: airflow-jwt-secret
  labels:
    tier: airflow
    app.kubernetes.io/part-of: airflow
type: Opaque
data:
  jwt-secret: {{ .Values.airflow.jwtSecret | b64enc | quote }}
