apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-jwt-secret
  namespace: airflow
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    jwt-secret: AgAfFz/TwMknv8pCDUnldMcP2WRfbZwL6WHnJZX0B3uc3ccLNHLuYyrcX2hdbteOpl8Ks05OIfYyqwcFyjoLsfEYg8T4/btinxWNin8CLEglgmkw3slPisufIk+JTG28Zm1n8hnOWkQZgzu07uTqPZBfcKX7BS+633C7yco00ho/FjpbFnGWfqSgoQMy75x2MotqKx7UqmXNlUhrUgZChal+iViHrRAake2xvZ05TEumlVtJ7156Rn+smfuQBomtLTpHwDO/92ZsRIDxKF9oJjotxj+KYqxyI3ZjsS6totBAInIju/5TrEMmOc9JFpjBojqvzdl21phTOM+//82Y0A7cTozhARk9MHPgG+Il0dEIsoGNaQszznzeWzc/wepqk9XsLxaKc7meMQU7vrWl2MgI0nkU7xSuqV49sMUp00xuDP64mL7VzgO5KUljFcD6BYsVE3JXIAQpMGpgR9cwUWK8Bzh+EjkCtU7B5LdMN5qrCenv5kwyUJrAUcVPc5rv/aOKs0hUaeFfJDvd6pzTNOuS3ALf8y2yBhQzDE3qQtHBWMQCWEibsN13NwAOkV5YPHSoAcU3UIh3Fxx5zt5s0Cbz6gjNjtkm2R+c/Naj7ZS0MlPpCqM5KWBJwAbB/PgZWWUej31x05aMyEpod5z/kO/Omqmp4CMHqtEykyMEp5dQBzSHSa+K7v5A1nbZO2V4KBGYaOqf0UVSysyzTKIEOVkdn3NDUkXp9MJoll1lwxuGH6XA5OQoiuSrj5Dxs1jplnN/wWI4ECbIbgQway8BuOzK
  template:
    metadata:
      name: airflow-jwt-secret
      namespace: airflow
      labels:
        tier: airflow
        app.kubernetes.io/part-of: airflow
    type: Opaque
